baseURL = 'https://example.org/'
languageCode = 'de-DE'
defaultContentLanguage = 'de'
title = 'Technik Basics'
theme = 'hugo-book'

enableGitInfo = true

[params]
bookTheme = 'light'
BookRepo = 'https://github.com/Simon-Martens/dok'
BookCommitPath = 'commit'
BookComments = false
BookDateFormat = "2. January 2006"
BookServiceWorker = true

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true
